#!/usr/bin/env perl

use strict;    # Still on 5.10, so need this for strict
use warnings;
use FindBin;                      # Find the location of seq-manipulations
use lib "$FindBin::Bin/lib";          # to use it as a lib path
require "SeqManipulations.pm";    # to get this library!
use 5.010;
use Getopt::Long qw(:config gnu_getopt);
use Pod::Usage;

################################################################################
# Option parsing
################################################################################
my %opts;
GetOptions(
    \%opts,
    "man|m",
    "help|h",
    "input|i=s",
    "output|o=s",
    "length|l",
    "numseq|n",
    "revcom|r",
    "pick|p=s",
    "delete|d=s",
    "translate|t=i", #Needs error checking
    "nogaps|g",
    "composition|c",
    "fetch|f=s", # Retrieve sequence by accession number
    "subseq|s=s",
    "anonymize|A:10",    # default 10 char (for phylip) (prefix + num_digits)  
    "break|B", 
    "reloop|R=i", # recircularize a genome at "loop_at"
    "linearize|L",
    "removestop|X", # for PAML/codeml    
    "leadgaps|G",
 #   "longest-orf|C", Retired for now
 #   "extract|e", Retired for now
 #   "dotplot|D=s", Retired for now
 #   "rename|N=s",  Retired for now
 #   "slidingwindow|S=i", Retired for now
 #   "prefix=s",   Retired for now
 #   "split|S=i", Retired for now

 
) or pod2usage(2);

pod2usage(1) if $opts{"help"};
pod2usage( -exitstatus => 0, -verbose => 2 ) if $opts{"man"};

################################################################################
# Main
################################################################################

# This sets all internal variables, and loads SeqIO objects
initialize( \%opts);

for my $option ( keys %opts ) {

    # Don't process these options: they are for SeqIO
    next if ( ( $option eq 'input' ) || ( $option eq 'output' ) );

    # If there is a function to handle the current option, execute it
    if ( can_handle($option) ) {
        handle_opt($option);
        exit;
    }
    else {
        warn "Missing handler for: $option\n";
    }
}

# Let seq-manipulations act as a converter when no other options are given.
write_out();

################# POD Documentation ##################

__END__

=head1 NAME

bioseq - FASTA file utility based on BioPerl.

=head1 SYNOPSIS

B<bioseq> [--help --man --composition --delete --fetch --nogaps --input --length --numseq --output --pick --revcom --subseq --translate --anonymize --break --leadgaps --linearize --reloop --removestop] <input_file>

B<bioseq> [-h -m -c -d=s -f=s -g -i=s -l -n -o=s -p=s -r -s=s -t=i -A:10 -B -G -L -R=i -X] <input_file>

=head1 DESCRIPTION

B<bioseq> is a UNIX-like command-line utility for common sequence manipulations. Most of the options are wrappers for the Bio::Seq class of BioPerl. By default, B<bioseq> will assume that both the input and the output are in FASTA format, so that multiple B<bioseq> runs can be chained with UNIX pipes.

=head1 OPTIONS

=head2 --help, -h

Print a brief help message and exit.

Usage: bioseq -h

=head2 --man, -m

Print the manual page and exit.

Usage: bioseq -m

=head2 --composition, -c

Base or AA composition.

Usage: bioseq -c <input_file>

=head2 --delete, -d

 Delete a sequence or a comma-separated list of sequences, eg,
 --del 'id:foo'		by id
 --del 'order:2'	by order
 --del 'length:n'	by min length, where 'n' is length
 --del 'ambig:x'	by min % ambiguous base/aa, where 'x' is the %
 --del 'id:foo,bar'	list by id
 --del 're:REGEX'       using a regular expression (only one regex is expected)

Usage: bioseq --delete 'tag:value' <input_file>

=head2 --fetch, -f
Retrieves a sequence from GenBank using the provided accession number.

Usage: bioseq -f <genbank_accession>

EXAMPLE:
    
bioseq -f 'X83553' -o 'genbank' (if want in genbank format; default is FASTA)

=head2 --nogaps, -g

Remove gaps

Usage: bioseq -g <input_file>

=head2 --input, -i

Input file format. By default, this is 'fasta'. For Genbank format, use 'genbank'. For EMBL format, use 'embl'.

Usage: bioseq -i 'format' <input_file>

=head2 --length, -l

Print all sequence lengths.

Usage: bioseq -l <input_file>

=head2 --numseq, -n

Print number of sequences in the input file.

Usage: bioseq -n <input_file>

=head2 --output, -o

Output file format. By default, this is 'fasta'. For Genbank format, use 'genbank'. For EMBL format, use 'embl'.

Usage: bioseq -o 'format' <input_file>

=head2 --pick, -p

Select a single sequence:
 --pick 'id:foo'        by id
 --pick 'order:2'       by order
 --pick 're:REGEX'      using a regular expression

Select a list of sequences:
 --pick 'id:foo,bar'    list by id
 --pick 'order:2,3'     list by order
 --pick 'order:2-10'    list by range

Usage: bioseq -p 'tag:value' <input_file>

=head2 --revcom, -r

Reverse complement

Usage: bioseq -r <input_file>

=head2 --subseq, -s

Select substring (of the 1st sequence), 

Usage: bioseq -s 'beginning_index, ending_index' <input_file>

Example:  bioseq -s'20,80' <input_file> (or -s='20,80')

=head2 --translate, -t

Translate in 1, 3, or 6 frames. eg, -t1, -t3, or -t6.

Usage: bioseq -t [1|3|6] <input_file>

=head2 --anonymize, -A

Replace sequence IDs with serial IDs 'n' characters long, including a leading 'S' (e.g., -A'5' gives S0001).
Produces a sed script file with a '.sed' suffix that may be used with sed's '-f' argument.
If the filename is '-', the sed file is named STDOUT.sed instead.
The sed filename is specified on STDERR.

Usage: bioseq -A 'number' <input_file>

=head2 --break, -B

Break into individual sequences, one sequence per file

Usage: bioseq -B <input_file>

=head2 --leadgaps, -G

Count and return the number of leading gaps in each sequence.

Usage: bioseq -G <input_file>

=head2 --linearize, -L

Linearize FASTA, one sequence per line

Usage: bioseq -L <input_file>

=head2 --reloop, -R

Re-circularize a bacterial genome by starting at a specified position, e.g. for sequence "ABCDE", bioseq -R'2' would generate 'BCDEA'.

Usage: bioseq --reloop 1000 <input_file>

=head2 --removestop, -X

Remove stop codons (e.g., PAML input)

Usage: bioseq -X <input_file>

=head1 REQUIRES

Perl 5.010, BioPerl

=head1 SEE ALSO

  perl(1)

=head1 AUTHORS

 Yozen Hernandez yzhernand at gmail dot com
 Levy Vargas levy dot vargas at gmail dot com
 Weigang Qiu at genectr.hunter.cuny.edu

=cut

##################### End ##########################
