name: osx

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:
    env:
      PREREQS: "Module::Build rlib Test::More Bio::Root::Version Bio::DB::GenBank Bio::Restriction::Analysis XML::DOM::XPath"

    runs-on: macos-latest

    strategy:
      matrix:
        os: [macOS]
        perl-version:
          - 'latest'
          - '5.32'
          - '5.30'
    steps:
     - uses: actions/checkout@v2
     - name: perl -V
       run: perl -V
     - name: Install Dependencies
       # By running cpanm this way without testing rather than using ./Build,
       # we save *a lot* of time.
       run: brew install cpanm && cpanm --notest $PREREQS
     - name: Run Tests
       run: perl Build.PL && ./Build && ./Build test
